### ISSUE TITLE
name change for io.py?

### ISSUE THREAD

**Issue by srodney** [jpierel14/sntd#2]
PyCharm apparently can in some cases have an issue with a package that contains modules with names that match up to certain core python system builtin modules, such as abc.py and io.py: 

https://stackoverflow.com/questions/26569828/pycharm-py-initialize-cant-initialize-sys-standard-streams

I suggest changing io.py to lightcurves.py, which I've just done in my fork.  If this isn't a problem for you, then it can wait until I issue a pull request to merge my fork into your dev branch.

**Comment by jpierel14** [comment]
Changed to curves_io.py
